/****************************************************************************
**
** Metadata for ActProgTypeLib generated by dumpcpp v5.13.0 using
** dumpcpp {78703D55-4042-4046-845D-7BBE83FB2F44}
** from the type library C:\MELSEC\Act\Control\ActProgType.dll
**
****************************************************************************/

#define QAX_DUMPCPP_ACTPROGTYPELIB_NOINLINES
#include "actprogtypelib.h"

using namespace ActProgTypeLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[211];
    char stringdata0[3320];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 27, 0),
QT_MOC_LITERAL(1, 28, 17, 0),
QT_MOC_LITERAL(2, 46, 19, 0),
QT_MOC_LITERAL(3, 66, 11, 0),
QT_MOC_LITERAL(4, 78, 12, 0),
QT_MOC_LITERAL(5, 91, 14, 0),
QT_MOC_LITERAL(6, 106, 0, 0),
QT_MOC_LITERAL(7, 107, 8, 0),
QT_MOC_LITERAL(8, 116, 5, 0),
QT_MOC_LITERAL(9, 122, 11, 0),
QT_MOC_LITERAL(10, 134, 9, 0),
QT_MOC_LITERAL(11, 144, 4, 0),
QT_MOC_LITERAL(12, 149, 6, 0),
QT_MOC_LITERAL(13, 156, 4, 0),
QT_MOC_LITERAL(14, 161, 4, 0),
QT_MOC_LITERAL(15, 166, 15, 0),
QT_MOC_LITERAL(16, 182, 4, 0),
QT_MOC_LITERAL(17, 187, 6, 0),
QT_MOC_LITERAL(18, 194, 4, 0),
QT_MOC_LITERAL(19, 199, 4, 0),
QT_MOC_LITERAL(20, 204, 17, 0),
QT_MOC_LITERAL(21, 222, 10, 0),
QT_MOC_LITERAL(22, 233, 5, 0),
QT_MOC_LITERAL(23, 239, 4, 0),
QT_MOC_LITERAL(24, 244, 13, 0),
QT_MOC_LITERAL(25, 258, 8, 0),
QT_MOC_LITERAL(26, 267, 14, 0),
QT_MOC_LITERAL(27, 282, 15, 0),
QT_MOC_LITERAL(28, 298, 14, 0),
QT_MOC_LITERAL(29, 313, 5, 0),
QT_MOC_LITERAL(30, 319, 7, 0),
QT_MOC_LITERAL(31, 327, 10, 0),
QT_MOC_LITERAL(32, 338, 17, 0),
QT_MOC_LITERAL(33, 356, 12, 0),
QT_MOC_LITERAL(34, 369, 13, 0),
QT_MOC_LITERAL(35, 383, 7, 0),
QT_MOC_LITERAL(36, 391, 16, 0),
QT_MOC_LITERAL(37, 408, 12, 0),
QT_MOC_LITERAL(38, 421, 7, 0),
QT_MOC_LITERAL(39, 429, 8, 0),
QT_MOC_LITERAL(40, 438, 6, 0),
QT_MOC_LITERAL(41, 445, 12, 0),
QT_MOC_LITERAL(42, 458, 7, 0),
QT_MOC_LITERAL(43, 466, 9, 0),
QT_MOC_LITERAL(44, 476, 9, 0),
QT_MOC_LITERAL(45, 486, 17, 0),
QT_MOC_LITERAL(46, 504, 8, 0),
QT_MOC_LITERAL(47, 513, 12, 0),
QT_MOC_LITERAL(48, 526, 10, 0),
QT_MOC_LITERAL(49, 537, 15, 0),
QT_MOC_LITERAL(50, 553, 10, 0),
QT_MOC_LITERAL(51, 564, 9, 0),
QT_MOC_LITERAL(52, 574, 10, 0),
QT_MOC_LITERAL(53, 585, 9, 0),
QT_MOC_LITERAL(54, 595, 10, 0),
QT_MOC_LITERAL(55, 606, 7, 0),
QT_MOC_LITERAL(56, 614, 4, 0),
QT_MOC_LITERAL(57, 619, 10, 0),
QT_MOC_LITERAL(58, 630, 8, 0),
QT_MOC_LITERAL(59, 639, 8, 0),
QT_MOC_LITERAL(60, 648, 15, 0),
QT_MOC_LITERAL(61, 664, 16, 0),
QT_MOC_LITERAL(62, 681, 16, 0),
QT_MOC_LITERAL(63, 698, 17, 0),
QT_MOC_LITERAL(64, 716, 15, 0),
QT_MOC_LITERAL(65, 732, 12, 0),
QT_MOC_LITERAL(66, 745, 39, 0),
QT_MOC_LITERAL(67, 785, 36, 0),
QT_MOC_LITERAL(68, 822, 31, 0),
QT_MOC_LITERAL(69, 854, 28, 0),
QT_MOC_LITERAL(70, 883, 14, 0),
QT_MOC_LITERAL(71, 898, 11, 0),
QT_MOC_LITERAL(72, 910, 28, 0),
QT_MOC_LITERAL(73, 939, 25, 0),
QT_MOC_LITERAL(74, 965, 23, 0),
QT_MOC_LITERAL(75, 989, 20, 0),
QT_MOC_LITERAL(76, 1010, 20, 0),
QT_MOC_LITERAL(77, 1031, 17, 0),
QT_MOC_LITERAL(78, 1049, 37, 0),
QT_MOC_LITERAL(79, 1087, 34, 0),
QT_MOC_LITERAL(80, 1122, 23, 0),
QT_MOC_LITERAL(81, 1146, 20, 0),
QT_MOC_LITERAL(82, 1167, 16, 0),
QT_MOC_LITERAL(83, 1184, 13, 0),
QT_MOC_LITERAL(84, 1198, 26, 0),
QT_MOC_LITERAL(85, 1225, 23, 0),
QT_MOC_LITERAL(86, 1249, 35, 0),
QT_MOC_LITERAL(87, 1285, 32, 0),
QT_MOC_LITERAL(88, 1318, 13, 0),
QT_MOC_LITERAL(89, 1332, 10, 0),
QT_MOC_LITERAL(90, 1343, 16, 0),
QT_MOC_LITERAL(91, 1360, 13, 0),
QT_MOC_LITERAL(92, 1374, 13, 0),
QT_MOC_LITERAL(93, 1388, 10, 0),
QT_MOC_LITERAL(94, 1399, 14, 0),
QT_MOC_LITERAL(95, 1414, 11, 0),
QT_MOC_LITERAL(96, 1426, 25, 0),
QT_MOC_LITERAL(97, 1452, 22, 0),
QT_MOC_LITERAL(98, 1475, 27, 0),
QT_MOC_LITERAL(99, 1503, 24, 0),
QT_MOC_LITERAL(100, 1528, 16, 0),
QT_MOC_LITERAL(101, 1545, 13, 0),
QT_MOC_LITERAL(102, 1559, 20, 0),
QT_MOC_LITERAL(103, 1580, 17, 0),
QT_MOC_LITERAL(104, 1598, 29, 0),
QT_MOC_LITERAL(105, 1628, 26, 0),
QT_MOC_LITERAL(106, 1655, 28, 0),
QT_MOC_LITERAL(107, 1684, 25, 0),
QT_MOC_LITERAL(108, 1710, 21, 0),
QT_MOC_LITERAL(109, 1732, 18, 0),
QT_MOC_LITERAL(110, 1751, 17, 0),
QT_MOC_LITERAL(111, 1769, 14, 0),
QT_MOC_LITERAL(112, 1784, 14, 0),
QT_MOC_LITERAL(113, 1799, 11, 0),
QT_MOC_LITERAL(114, 1811, 30, 0),
QT_MOC_LITERAL(115, 1842, 27, 0),
QT_MOC_LITERAL(116, 1870, 14, 0),
QT_MOC_LITERAL(117, 1885, 11, 0),
QT_MOC_LITERAL(118, 1897, 28, 0),
QT_MOC_LITERAL(119, 1926, 25, 0),
QT_MOC_LITERAL(120, 1952, 19, 0),
QT_MOC_LITERAL(121, 1972, 16, 0),
QT_MOC_LITERAL(122, 1989, 23, 0),
QT_MOC_LITERAL(123, 2013, 20, 0),
QT_MOC_LITERAL(124, 2034, 16, 0),
QT_MOC_LITERAL(125, 2051, 13, 0),
QT_MOC_LITERAL(126, 2065, 12, 0),
QT_MOC_LITERAL(127, 2078, 9, 0),
QT_MOC_LITERAL(128, 2088, 14, 0),
QT_MOC_LITERAL(129, 2103, 11, 0),
QT_MOC_LITERAL(130, 2115, 36, 0),
QT_MOC_LITERAL(131, 2152, 33, 0),
QT_MOC_LITERAL(132, 2186, 16, 0),
QT_MOC_LITERAL(133, 2203, 13, 0),
QT_MOC_LITERAL(134, 2217, 18, 0),
QT_MOC_LITERAL(135, 2236, 15, 0),
QT_MOC_LITERAL(136, 2252, 25, 0),
QT_MOC_LITERAL(137, 2278, 22, 0),
QT_MOC_LITERAL(138, 2301, 25, 0),
QT_MOC_LITERAL(139, 2327, 22, 0),
QT_MOC_LITERAL(140, 2350, 19, 0),
QT_MOC_LITERAL(141, 2370, 16, 0),
QT_MOC_LITERAL(142, 2387, 14, 0),
QT_MOC_LITERAL(143, 2402, 11, 0),
QT_MOC_LITERAL(144, 2414, 14, 0),
QT_MOC_LITERAL(145, 2429, 11, 0),
QT_MOC_LITERAL(146, 2441, 21, 0),
QT_MOC_LITERAL(147, 2463, 18, 0),
QT_MOC_LITERAL(148, 2482, 24, 0),
QT_MOC_LITERAL(149, 2507, 21, 0),
QT_MOC_LITERAL(150, 2529, 13, 0),
QT_MOC_LITERAL(151, 2543, 10, 0),
QT_MOC_LITERAL(152, 2554, 27, 0),
QT_MOC_LITERAL(153, 2582, 24, 0),
QT_MOC_LITERAL(154, 2607, 16, 0),
QT_MOC_LITERAL(155, 2624, 13, 0),
QT_MOC_LITERAL(156, 2638, 14, 0),
QT_MOC_LITERAL(157, 2653, 11, 0),
QT_MOC_LITERAL(158, 2665, 12, 0),
QT_MOC_LITERAL(159, 2678, 5, 0),
QT_MOC_LITERAL(160, 2684, 6, 0),
QT_MOC_LITERAL(161, 2691, 4, 0),
QT_MOC_LITERAL(162, 2696, 10, 0),
QT_MOC_LITERAL(163, 2707, 5, 0),
QT_MOC_LITERAL(164, 2713, 7, 0),
QT_MOC_LITERAL(165, 2721, 7, 0),
QT_MOC_LITERAL(166, 2729, 12, 0),
QT_MOC_LITERAL(167, 2742, 10, 0),
QT_MOC_LITERAL(168, 2753, 9, 0),
QT_MOC_LITERAL(169, 2763, 10, 0),
QT_MOC_LITERAL(170, 2774, 5, 0),
QT_MOC_LITERAL(171, 2780, 11, 0),
QT_MOC_LITERAL(172, 2792, 16, 0),
QT_MOC_LITERAL(173, 2809, 17, 0),
QT_MOC_LITERAL(174, 2827, 17, 0),
QT_MOC_LITERAL(175, 2845, 18, 0),
QT_MOC_LITERAL(176, 2864, 28, 0),
QT_MOC_LITERAL(177, 2893, 7, 0),
QT_MOC_LITERAL(178, 2901, 29, 0),
QT_MOC_LITERAL(179, 2931, 21, 0),
QT_MOC_LITERAL(180, 2953, 14, 0),
QT_MOC_LITERAL(181, 2968, 9, 0),
QT_MOC_LITERAL(182, 2978, 7, 0),
QT_MOC_LITERAL(183, 2986, 13, 0),
QT_MOC_LITERAL(184, 3000, 13, 0),
QT_MOC_LITERAL(185, 3014, 7, 0),
QT_MOC_LITERAL(186, 3022, 15, 0),
QT_MOC_LITERAL(187, 3038, 9, 0),
QT_MOC_LITERAL(188, 3048, 9, 0),
QT_MOC_LITERAL(189, 3058, 10, 0),
QT_MOC_LITERAL(190, 3069, 8, 0),
QT_MOC_LITERAL(191, 3078, 14, 0),
QT_MOC_LITERAL(192, 3093, 9, 0),
QT_MOC_LITERAL(193, 3103, 11, 0),
QT_MOC_LITERAL(194, 3115, 11, 0),
QT_MOC_LITERAL(195, 3127, 12, 0),
QT_MOC_LITERAL(196, 3140, 12, 0),
QT_MOC_LITERAL(197, 3153, 9, 0),
QT_MOC_LITERAL(198, 3163, 10, 0),
QT_MOC_LITERAL(199, 3174, 10, 0),
QT_MOC_LITERAL(200, 3185, 11, 0),
QT_MOC_LITERAL(201, 3197, 7, 0),
QT_MOC_LITERAL(202, 3205, 8, 0),
QT_MOC_LITERAL(203, 3214, 6, 0),
QT_MOC_LITERAL(204, 3221, 12, 0),
QT_MOC_LITERAL(205, 3234, 7, 0),
QT_MOC_LITERAL(206, 3242, 9, 0),
QT_MOC_LITERAL(207, 3252, 9, 0),
QT_MOC_LITERAL(208, 3262, 12, 0),
QT_MOC_LITERAL(209, 3275, 12, 0),
QT_MOC_LITERAL(210, 3288, 30, 0)
    },
    "ActProgTypeLib::ActProgType\0Event Interface 1\0_IActProgTypeEvents\0Interface 0\0"
    "IActProgType\0OnDeviceStatus\0\0szDevice\0lData\0lReturnCode\0exception\0code\0source\0"
    "disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0CheckDeviceString\0lCheckType\0"
    "lSize\0int&\0lplDeviceType\0QString&\0lpszDeviceName\0lplDeviceNumber\0lplDeviceRadix\0"
    "Close\0Connect\0Disconnect\0EntryDeviceStatus\0szDeviceList\0lMonitorCycle\0lplData\0"
    "FreeDeviceStatus\0GetClockData\0lpsYear\0lpsMonth\0lpsDay\0lpsDayOfWeek\0lpsHour\0"
    "lpsMinute\0lpsSecond\0GetCpuListOnEther\0lTimeOut\0lCpuListSize\0lplCpuList\0"
    "lplCpuListCount\0GetCpuType\0szCpuName\0lplCpuCode\0GetDevice\0GetDevice2\0lpsData\0"
    "Open\0ReadBuffer\0lStartIO\0lAddress\0ReadDeviceBlock\0ReadDeviceBlock2\0"
    "ReadDeviceRandom\0ReadDeviceRandom2\0SetActATCommand\0ActATCommand\0"
    "SetActATCommandPasswordCancelRetryTimes\0ActATCommandPasswordCancelRetryTimes\0"
    "SetActATCommandResponseWaitTime\0ActATCommandResponseWaitTime\0SetActBaudRate\0"
    "ActBaudRate\0SetActCallbackCancelWaitTime\0ActCallbackCancelWaitTime\0"
    "SetActCallbackDelayTime\0ActCallbackDelayTime\0SetActCallbackNumber\0ActCallbackNumber\0"
    "SetActCallbackReceptionWaitingTimeOut\0ActCallbackReceptionWaitingTimeOut\0"
    "SetActConnectUnitNumber\0ActConnectUnitNumber\0SetActConnectWay\0ActConnectWay\0"
    "SetActConnectionCDWaitTime\0ActConnectionCDWaitTime\0SetActConnectionModemReportWaitTime\0"
    "ActConnectionModemReportWaitTime\0SetActControl\0ActControl\0SetActCpuTimeOut\0"
    "ActCpuTimeOut\0SetActCpuType\0ActCpuType\0SetActDataBits\0ActDataBits\0"
    "SetActDestinationIONumber\0ActDestinationIONumber\0SetActDestinationPortNumber\0"
    "ActDestinationPortNumber\0SetActDialNumber\0ActDialNumber\0SetActDidPropertyBit\0"
    "ActDidPropertyBit\0SetActDisconnectionCDWaitTime\0ActDisconnectionCDWaitTime\0"
    "SetActDisconnectionDelayTime\0ActDisconnectionDelayTime\0SetActDsidPropertyBit\0"
    "ActDsidPropertyBit\0SetActHostAddress\0ActHostAddress\0SetActIONumber\0ActIONumber\0"
    "SetActIntelligentPreferenceBit\0ActIntelligentPreferenceBit\0SetActLineType\0"
    "ActLineType\0SetActMultiDropChannelNumber\0ActMultiDropChannelNumber\0"
    "SetActNetworkNumber\0ActNetworkNumber\0SetActOutsideLineNumber\0ActOutsideLineNumber\0"
    "SetActPacketType\0ActPacketType\0SetActParity\0ActParity\0SetActPassword\0ActPassword\0"
    "SetActPasswordCancelResponseWaitTime\0ActPasswordCancelResponseWaitTime\0"
    "SetActPortNumber\0ActPortNumber\0SetActProtocolType\0ActProtocolType\0"
    "SetActSourceNetworkNumber\0ActSourceNetworkNumber\0SetActSourceStationNumber\0"
    "ActSourceStationNumber\0SetActStationNumber\0ActStationNumber\0SetActStopBits\0"
    "ActStopBits\0SetActSumCheck\0ActSumCheck\0SetActTargetSimulator\0ActTargetSimulator\0"
    "SetActThroughNetworkType\0ActThroughNetworkType\0SetActTimeOut\0ActTimeOut\0"
    "SetActTransmissionDelayTime\0ActTransmissionDelayTime\0SetActUnitNumber\0"
    "ActUnitNumber\0SetActUnitType\0ActUnitType\0SetClockData\0sYear\0sMonth\0sDay\0"
    "sDayOfWeek\0sHour\0sMinute\0sSecond\0SetCpuStatus\0lOperation\0SetDevice\0SetDevice2\0"
    "sData\0WriteBuffer\0WriteDeviceBlock\0WriteDeviceBlock2\0WriteDeviceRandom\0"
    "WriteDeviceRandom2\0ActProgTypeLib::IActProgType\0control\0ActProgTypeLib::ActMLProgType\0"
    "_IActMLProgTypeEvents\0IActMLProgType\0varDevice\0varData\0varReturnCode\0"
    "varDeviceList\0varSize\0varMonitorCycle\0QVariant&\0lpvarYear\0lpvarMonth\0lpvarDay\0"
    "lpvarDayOfWeek\0lpvarHour\0lpvarMinute\0lpvarSecond\0lpvarCpuName\0lpvarCpuCode\0"
    "lpvarData\0varStartIO\0varAddress\0varReadSize\0varYear\0varMonth\0varDay\0varDayOfWeek\0"
    "varHour\0varMinute\0varSecond\0varOperation\0varWriteSize\0ActProgTypeLib::IActMLProgType\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_ActProgTypeLib__ActProgType[] = {

 // content:
    7, // revision
    0,  // classname
    2, 14, // classinfo
    77, 18, // methods
    47, 740, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 

// signal: name, argc, parameters, tag, flags
    5, 3, 403, 6, 5,
    10, 4, 410, 6, 5,
    15, 1, 419, 6, 5,
    17, 3, 422, 6, 5,

// slot: name, argc, parameters, tag, flags
    20, 7, 429, 6, 9,
    29, 0, 444, 6, 9,
    30, 0, 445, 6, 9,
    31, 0, 446, 6, 9,
    32, 4, 447, 6, 9,
    36, 0, 456, 6, 9,
    37, 7, 457, 6, 9,
    45, 4, 472, 6, 9,
    50, 2, 481, 6, 9,
    53, 2, 486, 6, 9,
    54, 2, 491, 6, 9,
    56, 0, 496, 6, 9,
    57, 4, 497, 6, 9,
    60, 3, 506, 6, 9,
    61, 3, 513, 6, 9,
    62, 3, 520, 6, 9,
    63, 3, 527, 6, 9,
    64, 1, 534, 6, 9,
    66, 1, 537, 6, 9,
    68, 1, 540, 6, 9,
    70, 1, 543, 6, 9,
    72, 1, 546, 6, 9,
    74, 1, 549, 6, 9,
    76, 1, 552, 6, 9,
    78, 1, 555, 6, 9,
    80, 1, 558, 6, 9,
    82, 1, 561, 6, 9,
    84, 1, 564, 6, 9,
    86, 1, 567, 6, 9,
    88, 1, 570, 6, 9,
    90, 1, 573, 6, 9,
    92, 1, 576, 6, 9,
    94, 1, 579, 6, 9,
    96, 1, 582, 6, 9,
    98, 1, 585, 6, 9,
    100, 1, 588, 6, 9,
    102, 1, 591, 6, 9,
    104, 1, 594, 6, 9,
    106, 1, 597, 6, 9,
    108, 1, 600, 6, 9,
    110, 1, 603, 6, 9,
    112, 1, 606, 6, 9,
    114, 1, 609, 6, 9,
    116, 1, 612, 6, 9,
    118, 1, 615, 6, 9,
    120, 1, 618, 6, 9,
    122, 1, 621, 6, 9,
    124, 1, 624, 6, 9,
    126, 1, 627, 6, 9,
    128, 1, 630, 6, 9,
    130, 1, 633, 6, 9,
    132, 1, 636, 6, 9,
    134, 1, 639, 6, 9,
    136, 1, 642, 6, 9,
    138, 1, 645, 6, 9,
    140, 1, 648, 6, 9,
    142, 1, 651, 6, 9,
    144, 1, 654, 6, 9,
    146, 1, 657, 6, 9,
    148, 1, 660, 6, 9,
    150, 1, 663, 6, 9,
    152, 1, 666, 6, 9,
    154, 1, 669, 6, 9,
    156, 1, 672, 6, 9,
    158, 7, 675, 6, 9,
    166, 1, 690, 6, 9,
    168, 2, 693, 6, 9,
    169, 2, 698, 6, 9,
    171, 4, 703, 6, 9,
    172, 3, 712, 6, 9,
    173, 3, 719, 6, 9,
    174, 3, 726, 6, 9,
    175, 3, 733, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::Int, 7, 8, 9,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 0x80000000 | 25, 0x80000000 | 23, 0x80000000 | 23, 7, 21, 22, 24, 26, 27, 28,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 33, 22, 34, 35,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 38, 39, 40, 41, 42, 43, 44,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 0x80000000 | 23, 46, 47, 48, 49,
    QMetaType::Int, 0x80000000 | 25, 0x80000000 | 23, 51, 52,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 23, 7, 35,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 23, 7, 55,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 58, 59, 22, 55,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 55,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 55,
    QMetaType::Void, QMetaType::QString, 65,
    QMetaType::Void, QMetaType::Int, 67,
    QMetaType::Void, QMetaType::Int, 69,
    QMetaType::Void, QMetaType::Int, 71,
    QMetaType::Void, QMetaType::Int, 73,
    QMetaType::Void, QMetaType::Int, 75,
    QMetaType::Void, QMetaType::QString, 77,
    QMetaType::Void, QMetaType::Int, 79,
    QMetaType::Void, QMetaType::Int, 81,
    QMetaType::Void, QMetaType::Int, 83,
    QMetaType::Void, QMetaType::Int, 85,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, QMetaType::Int, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::QString, 101,
    QMetaType::Void, QMetaType::Int, 103,
    QMetaType::Void, QMetaType::Int, 105,
    QMetaType::Void, QMetaType::Int, 107,
    QMetaType::Void, QMetaType::Int, 109,
    QMetaType::Void, QMetaType::QString, 111,
    QMetaType::Void, QMetaType::Int, 113,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void, QMetaType::Int, 117,
    QMetaType::Void, QMetaType::Int, 119,
    QMetaType::Void, QMetaType::Int, 121,
    QMetaType::Void, QMetaType::QString, 123,
    QMetaType::Void, QMetaType::Int, 125,
    QMetaType::Void, QMetaType::Int, 127,
    QMetaType::Void, QMetaType::QString, 129,
    QMetaType::Void, QMetaType::Int, 131,
    QMetaType::Void, QMetaType::Int, 133,
    QMetaType::Void, QMetaType::Int, 135,
    QMetaType::Void, QMetaType::Int, 137,
    QMetaType::Void, QMetaType::Int, 139,
    QMetaType::Void, QMetaType::Int, 141,
    QMetaType::Void, QMetaType::Int, 143,
    QMetaType::Void, QMetaType::Int, 145,
    QMetaType::Void, QMetaType::Int, 147,
    QMetaType::Void, QMetaType::Int, 149,
    QMetaType::Void, QMetaType::Int, 151,
    QMetaType::Void, QMetaType::Int, 153,
    QMetaType::Void, QMetaType::Int, 155,
    QMetaType::Void, QMetaType::Int, 157,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 159, 160, 161, 162, 163, 164, 165,
    QMetaType::Int, QMetaType::Int, 167,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 7, 8,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 7, 170,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 58, 59, 22, 55,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 55,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 55,

 // properties: name, type, flags
    65, QMetaType::QString, 0x0a015003, 		 // QString ActATCommand
    67, QMetaType::Int, 0x02015003, 		 // int ActATCommandPasswordCancelRetryTimes
    69, QMetaType::Int, 0x02015003, 		 // int ActATCommandResponseWaitTime
    71, QMetaType::Int, 0x02015003, 		 // int ActBaudRate
    73, QMetaType::Int, 0x02015003, 		 // int ActCallbackCancelWaitTime
    75, QMetaType::Int, 0x02015003, 		 // int ActCallbackDelayTime
    77, QMetaType::QString, 0x0a015003, 		 // QString ActCallbackNumber
    79, QMetaType::Int, 0x02015003, 		 // int ActCallbackReceptionWaitingTimeOut
    81, QMetaType::Int, 0x02015003, 		 // int ActConnectUnitNumber
    83, QMetaType::Int, 0x02015003, 		 // int ActConnectWay
    85, QMetaType::Int, 0x02015003, 		 // int ActConnectionCDWaitTime
    87, QMetaType::Int, 0x02015003, 		 // int ActConnectionModemReportWaitTime
    89, QMetaType::Int, 0x02015003, 		 // int ActControl
    91, QMetaType::Int, 0x02015003, 		 // int ActCpuTimeOut
    93, QMetaType::Int, 0x02015003, 		 // int ActCpuType
    95, QMetaType::Int, 0x02015003, 		 // int ActDataBits
    97, QMetaType::Int, 0x02015003, 		 // int ActDestinationIONumber
    99, QMetaType::Int, 0x02015003, 		 // int ActDestinationPortNumber
    101, QMetaType::QString, 0x0a015003, 		 // QString ActDialNumber
    103, QMetaType::Int, 0x02015003, 		 // int ActDidPropertyBit
    105, QMetaType::Int, 0x02015003, 		 // int ActDisconnectionCDWaitTime
    107, QMetaType::Int, 0x02015003, 		 // int ActDisconnectionDelayTime
    109, QMetaType::Int, 0x02015003, 		 // int ActDsidPropertyBit
    111, QMetaType::QString, 0x0a015003, 		 // QString ActHostAddress
    113, QMetaType::Int, 0x02015003, 		 // int ActIONumber
    115, QMetaType::Int, 0x02015003, 		 // int ActIntelligentPreferenceBit
    117, QMetaType::Int, 0x02015003, 		 // int ActLineType
    119, QMetaType::Int, 0x02015003, 		 // int ActMultiDropChannelNumber
    121, QMetaType::Int, 0x02015003, 		 // int ActNetworkNumber
    123, QMetaType::QString, 0x0a015003, 		 // QString ActOutsideLineNumber
    125, QMetaType::Int, 0x02015003, 		 // int ActPacketType
    127, QMetaType::Int, 0x02015003, 		 // int ActParity
    129, QMetaType::QString, 0x0a015003, 		 // QString ActPassword
    131, QMetaType::Int, 0x02015003, 		 // int ActPasswordCancelResponseWaitTime
    133, QMetaType::Int, 0x02015003, 		 // int ActPortNumber
    135, QMetaType::Int, 0x02015003, 		 // int ActProtocolType
    137, QMetaType::Int, 0x02015003, 		 // int ActSourceNetworkNumber
    139, QMetaType::Int, 0x02015003, 		 // int ActSourceStationNumber
    141, QMetaType::Int, 0x02015003, 		 // int ActStationNumber
    143, QMetaType::Int, 0x02015003, 		 // int ActStopBits
    145, QMetaType::Int, 0x02015003, 		 // int ActSumCheck
    147, QMetaType::Int, 0x02015003, 		 // int ActTargetSimulator
    149, QMetaType::Int, 0x02015003, 		 // int ActThroughNetworkType
    151, QMetaType::Int, 0x02015003, 		 // int ActTimeOut
    153, QMetaType::Int, 0x02015003, 		 // int ActTransmissionDelayTime
    155, QMetaType::Int, 0x02015003, 		 // int ActUnitNumber
    157, QMetaType::Int, 0x02015003, 		 // int ActUnitType

    0 // eod
};

const QMetaObject ActProgType::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActProgTypeLib__ActProgType, 0, 0, 0 }
};

void *ActProgType::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ActProgTypeLib::ActProgType"))
        return static_cast<void*>(const_cast<ActProgType*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_ActProgTypeLib__IActProgType[] = {

 // content:
    7, // revision
    176,  // classname
    0, 0, // classinfo
    76, 14, // methods
    48, 724, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 394, 6, 5,
    15, 1, 403, 6, 5,
    17, 3, 406, 6, 5,

// slot: name, argc, parameters, tag, flags
    20, 7, 413, 6, 9,
    29, 0, 428, 6, 9,
    30, 0, 429, 6, 9,
    31, 0, 430, 6, 9,
    32, 4, 431, 6, 9,
    36, 0, 440, 6, 9,
    37, 7, 441, 6, 9,
    45, 4, 456, 6, 9,
    50, 2, 465, 6, 9,
    53, 2, 470, 6, 9,
    54, 2, 475, 6, 9,
    56, 0, 480, 6, 9,
    57, 4, 481, 6, 9,
    60, 3, 490, 6, 9,
    61, 3, 497, 6, 9,
    62, 3, 504, 6, 9,
    63, 3, 511, 6, 9,
    64, 1, 518, 6, 9,
    66, 1, 521, 6, 9,
    68, 1, 524, 6, 9,
    70, 1, 527, 6, 9,
    72, 1, 530, 6, 9,
    74, 1, 533, 6, 9,
    76, 1, 536, 6, 9,
    78, 1, 539, 6, 9,
    80, 1, 542, 6, 9,
    82, 1, 545, 6, 9,
    84, 1, 548, 6, 9,
    86, 1, 551, 6, 9,
    88, 1, 554, 6, 9,
    90, 1, 557, 6, 9,
    92, 1, 560, 6, 9,
    94, 1, 563, 6, 9,
    96, 1, 566, 6, 9,
    98, 1, 569, 6, 9,
    100, 1, 572, 6, 9,
    102, 1, 575, 6, 9,
    104, 1, 578, 6, 9,
    106, 1, 581, 6, 9,
    108, 1, 584, 6, 9,
    110, 1, 587, 6, 9,
    112, 1, 590, 6, 9,
    114, 1, 593, 6, 9,
    116, 1, 596, 6, 9,
    118, 1, 599, 6, 9,
    120, 1, 602, 6, 9,
    122, 1, 605, 6, 9,
    124, 1, 608, 6, 9,
    126, 1, 611, 6, 9,
    128, 1, 614, 6, 9,
    130, 1, 617, 6, 9,
    132, 1, 620, 6, 9,
    134, 1, 623, 6, 9,
    136, 1, 626, 6, 9,
    138, 1, 629, 6, 9,
    140, 1, 632, 6, 9,
    142, 1, 635, 6, 9,
    144, 1, 638, 6, 9,
    146, 1, 641, 6, 9,
    148, 1, 644, 6, 9,
    150, 1, 647, 6, 9,
    152, 1, 650, 6, 9,
    154, 1, 653, 6, 9,
    156, 1, 656, 6, 9,
    158, 7, 659, 6, 9,
    166, 1, 674, 6, 9,
    168, 2, 677, 6, 9,
    169, 2, 682, 6, 9,
    171, 4, 687, 6, 9,
    172, 3, 696, 6, 9,
    173, 3, 703, 6, 9,
    174, 3, 710, 6, 9,
    175, 3, 717, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 0x80000000 | 25, 0x80000000 | 23, 0x80000000 | 23, 7, 21, 22, 24, 26, 27, 28,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 33, 22, 34, 35,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 38, 39, 40, 41, 42, 43, 44,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 0x80000000 | 23, 46, 47, 48, 49,
    QMetaType::Int, 0x80000000 | 25, 0x80000000 | 23, 51, 52,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 23, 7, 35,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 23, 7, 55,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 58, 59, 22, 55,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 55,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 55,
    QMetaType::Void, QMetaType::QString, 65,
    QMetaType::Void, QMetaType::Int, 67,
    QMetaType::Void, QMetaType::Int, 69,
    QMetaType::Void, QMetaType::Int, 71,
    QMetaType::Void, QMetaType::Int, 73,
    QMetaType::Void, QMetaType::Int, 75,
    QMetaType::Void, QMetaType::QString, 77,
    QMetaType::Void, QMetaType::Int, 79,
    QMetaType::Void, QMetaType::Int, 81,
    QMetaType::Void, QMetaType::Int, 83,
    QMetaType::Void, QMetaType::Int, 85,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, QMetaType::Int, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::QString, 101,
    QMetaType::Void, QMetaType::Int, 103,
    QMetaType::Void, QMetaType::Int, 105,
    QMetaType::Void, QMetaType::Int, 107,
    QMetaType::Void, QMetaType::Int, 109,
    QMetaType::Void, QMetaType::QString, 111,
    QMetaType::Void, QMetaType::Int, 113,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void, QMetaType::Int, 117,
    QMetaType::Void, QMetaType::Int, 119,
    QMetaType::Void, QMetaType::Int, 121,
    QMetaType::Void, QMetaType::QString, 123,
    QMetaType::Void, QMetaType::Int, 125,
    QMetaType::Void, QMetaType::Int, 127,
    QMetaType::Void, QMetaType::QString, 129,
    QMetaType::Void, QMetaType::Int, 131,
    QMetaType::Void, QMetaType::Int, 133,
    QMetaType::Void, QMetaType::Int, 135,
    QMetaType::Void, QMetaType::Int, 137,
    QMetaType::Void, QMetaType::Int, 139,
    QMetaType::Void, QMetaType::Int, 141,
    QMetaType::Void, QMetaType::Int, 143,
    QMetaType::Void, QMetaType::Int, 145,
    QMetaType::Void, QMetaType::Int, 147,
    QMetaType::Void, QMetaType::Int, 149,
    QMetaType::Void, QMetaType::Int, 151,
    QMetaType::Void, QMetaType::Int, 153,
    QMetaType::Void, QMetaType::Int, 155,
    QMetaType::Void, QMetaType::Int, 157,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 159, 160, 161, 162, 163, 164, 165,
    QMetaType::Int, QMetaType::Int, 167,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 7, 8,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 7, 170,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 58, 59, 22, 55,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 55,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 55,

 // properties: name, type, flags
    65, QMetaType::QString, 0x0a015003, 		 // QString ActATCommand
    67, QMetaType::Int, 0x02015003, 		 // int ActATCommandPasswordCancelRetryTimes
    69, QMetaType::Int, 0x02015003, 		 // int ActATCommandResponseWaitTime
    71, QMetaType::Int, 0x02015003, 		 // int ActBaudRate
    73, QMetaType::Int, 0x02015003, 		 // int ActCallbackCancelWaitTime
    75, QMetaType::Int, 0x02015003, 		 // int ActCallbackDelayTime
    77, QMetaType::QString, 0x0a015003, 		 // QString ActCallbackNumber
    79, QMetaType::Int, 0x02015003, 		 // int ActCallbackReceptionWaitingTimeOut
    81, QMetaType::Int, 0x02015003, 		 // int ActConnectUnitNumber
    83, QMetaType::Int, 0x02015003, 		 // int ActConnectWay
    85, QMetaType::Int, 0x02015003, 		 // int ActConnectionCDWaitTime
    87, QMetaType::Int, 0x02015003, 		 // int ActConnectionModemReportWaitTime
    89, QMetaType::Int, 0x02015003, 		 // int ActControl
    91, QMetaType::Int, 0x02015003, 		 // int ActCpuTimeOut
    93, QMetaType::Int, 0x02015003, 		 // int ActCpuType
    95, QMetaType::Int, 0x02015003, 		 // int ActDataBits
    97, QMetaType::Int, 0x02015003, 		 // int ActDestinationIONumber
    99, QMetaType::Int, 0x02015003, 		 // int ActDestinationPortNumber
    101, QMetaType::QString, 0x0a015003, 		 // QString ActDialNumber
    103, QMetaType::Int, 0x02015003, 		 // int ActDidPropertyBit
    105, QMetaType::Int, 0x02015003, 		 // int ActDisconnectionCDWaitTime
    107, QMetaType::Int, 0x02015003, 		 // int ActDisconnectionDelayTime
    109, QMetaType::Int, 0x02015003, 		 // int ActDsidPropertyBit
    111, QMetaType::QString, 0x0a015003, 		 // QString ActHostAddress
    113, QMetaType::Int, 0x02015003, 		 // int ActIONumber
    115, QMetaType::Int, 0x02015003, 		 // int ActIntelligentPreferenceBit
    117, QMetaType::Int, 0x02015003, 		 // int ActLineType
    119, QMetaType::Int, 0x02015003, 		 // int ActMultiDropChannelNumber
    121, QMetaType::Int, 0x02015003, 		 // int ActNetworkNumber
    123, QMetaType::QString, 0x0a015003, 		 // QString ActOutsideLineNumber
    125, QMetaType::Int, 0x02015003, 		 // int ActPacketType
    127, QMetaType::Int, 0x02015003, 		 // int ActParity
    129, QMetaType::QString, 0x0a015003, 		 // QString ActPassword
    131, QMetaType::Int, 0x02015003, 		 // int ActPasswordCancelResponseWaitTime
    133, QMetaType::Int, 0x02015003, 		 // int ActPortNumber
    135, QMetaType::Int, 0x02015003, 		 // int ActProtocolType
    137, QMetaType::Int, 0x02015003, 		 // int ActSourceNetworkNumber
    139, QMetaType::Int, 0x02015003, 		 // int ActSourceStationNumber
    141, QMetaType::Int, 0x02015003, 		 // int ActStationNumber
    143, QMetaType::Int, 0x02015003, 		 // int ActStopBits
    145, QMetaType::Int, 0x02015003, 		 // int ActSumCheck
    147, QMetaType::Int, 0x02015003, 		 // int ActTargetSimulator
    149, QMetaType::Int, 0x02015003, 		 // int ActThroughNetworkType
    151, QMetaType::Int, 0x02015003, 		 // int ActTimeOut
    153, QMetaType::Int, 0x02015003, 		 // int ActTransmissionDelayTime
    155, QMetaType::Int, 0x02015003, 		 // int ActUnitNumber
    157, QMetaType::Int, 0x02015003, 		 // int ActUnitType
    177, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IActProgType::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActProgTypeLib__IActProgType, 0, 0, 0 }
};

void *IActProgType::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ActProgTypeLib::IActProgType"))
        return static_cast<void*>(const_cast<IActProgType*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_ActProgTypeLib__ActMLProgType[] = {

 // content:
    7, // revision
    178,  // classname
    2, 14, // classinfo
    56, 18, // methods
    30, 558, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    1, 179, 
    3, 180, 

// signal: name, argc, parameters, tag, flags
    5, 3, 298, 6, 5,
    10, 4, 305, 6, 5,
    15, 1, 314, 6, 5,
    17, 3, 317, 6, 5,

// slot: name, argc, parameters, tag, flags
    29, 0, 324, 6, 9,
    32, 4, 325, 6, 9,
    36, 0, 334, 6, 9,
    37, 7, 335, 6, 9,
    50, 2, 350, 6, 9,
    53, 2, 355, 6, 9,
    54, 2, 360, 6, 9,
    56, 0, 365, 6, 9,
    57, 4, 366, 6, 9,
    60, 3, 375, 6, 9,
    61, 3, 382, 6, 9,
    62, 3, 389, 6, 9,
    63, 3, 396, 6, 9,
    70, 1, 403, 6, 9,
    80, 1, 406, 6, 9,
    88, 1, 409, 6, 9,
    90, 1, 412, 6, 9,
    92, 1, 415, 6, 9,
    94, 1, 418, 6, 9,
    96, 1, 421, 6, 9,
    98, 1, 424, 6, 9,
    102, 1, 427, 6, 9,
    108, 1, 430, 6, 9,
    110, 1, 433, 6, 9,
    112, 1, 436, 6, 9,
    114, 1, 439, 6, 9,
    118, 1, 442, 6, 9,
    120, 1, 445, 6, 9,
    124, 1, 448, 6, 9,
    126, 1, 451, 6, 9,
    128, 1, 454, 6, 9,
    132, 1, 457, 6, 9,
    134, 1, 460, 6, 9,
    136, 1, 463, 6, 9,
    138, 1, 466, 6, 9,
    140, 1, 469, 6, 9,
    142, 1, 472, 6, 9,
    144, 1, 475, 6, 9,
    146, 1, 478, 6, 9,
    148, 1, 481, 6, 9,
    150, 1, 484, 6, 9,
    154, 1, 487, 6, 9,
    156, 1, 490, 6, 9,
    158, 7, 493, 6, 9,
    166, 1, 508, 6, 9,
    168, 2, 511, 6, 9,
    169, 2, 516, 6, 9,
    171, 4, 521, 6, 9,
    172, 3, 530, 6, 9,
    173, 3, 537, 6, 9,
    174, 3, 544, 6, 9,
    175, 3, 551, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 182, 183,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 184, 185, 186, 182,
    QMetaType::QVariant,
    QMetaType::QVariant, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 188, 189, 190, 191, 192, 193, 194,
    QMetaType::QVariant, 0x80000000 | 187, 0x80000000 | 187, 195, 196,
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 181, 197,
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 181, 197,
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 198, 199, 200, 197,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 181, 185, 197,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 181, 185, 197,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 184, 185, 197,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 184, 185, 197,
    QMetaType::Void, QMetaType::QVariant, 71,
    QMetaType::Void, QMetaType::QVariant, 81,
    QMetaType::Void, QMetaType::QVariant, 89,
    QMetaType::Void, QMetaType::QVariant, 91,
    QMetaType::Void, QMetaType::QVariant, 93,
    QMetaType::Void, QMetaType::QVariant, 95,
    QMetaType::Void, QMetaType::QVariant, 97,
    QMetaType::Void, QMetaType::QVariant, 99,
    QMetaType::Void, QMetaType::QVariant, 103,
    QMetaType::Void, QMetaType::QVariant, 109,
    QMetaType::Void, QMetaType::QVariant, 111,
    QMetaType::Void, QMetaType::QVariant, 113,
    QMetaType::Void, QMetaType::QVariant, 115,
    QMetaType::Void, QMetaType::QVariant, 119,
    QMetaType::Void, QMetaType::QVariant, 121,
    QMetaType::Void, QMetaType::QVariant, 125,
    QMetaType::Void, QMetaType::QVariant, 127,
    QMetaType::Void, QMetaType::QVariant, 129,
    QMetaType::Void, QMetaType::QVariant, 133,
    QMetaType::Void, QMetaType::QVariant, 135,
    QMetaType::Void, QMetaType::QVariant, 137,
    QMetaType::Void, QMetaType::QVariant, 139,
    QMetaType::Void, QMetaType::QVariant, 141,
    QMetaType::Void, QMetaType::QVariant, 143,
    QMetaType::Void, QMetaType::QVariant, 145,
    QMetaType::Void, QMetaType::QVariant, 147,
    QMetaType::Void, QMetaType::QVariant, 149,
    QMetaType::Void, QMetaType::QVariant, 151,
    QMetaType::Void, QMetaType::QVariant, 155,
    QMetaType::Void, QMetaType::QVariant, 157,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 201, 202, 203, 204, 205, 206, 207,
    QMetaType::QVariant, QMetaType::QVariant, 208,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 198, 199, 209, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 185, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 185, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 184, 185, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 184, 185, 182,

 // properties: name, type, flags
    71, QMetaType::QVariant, 0x29015003, 		 // QVariant ActBaudRate
    81, QMetaType::QVariant, 0x29015003, 		 // QVariant ActConnectUnitNumber
    89, QMetaType::QVariant, 0x29015003, 		 // QVariant ActControl
    91, QMetaType::QVariant, 0x29015003, 		 // QVariant ActCpuTimeOut
    93, QMetaType::QVariant, 0x29015003, 		 // QVariant ActCpuType
    95, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDataBits
    97, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDestinationIONumber
    99, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDestinationPortNumber
    103, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDidPropertyBit
    109, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDsidPropertyBit
    111, QMetaType::QVariant, 0x29015003, 		 // QVariant ActHostAddress
    113, QMetaType::QVariant, 0x29015003, 		 // QVariant ActIONumber
    115, QMetaType::QVariant, 0x29015003, 		 // QVariant ActIntelligentPreferenceBit
    119, QMetaType::QVariant, 0x29015003, 		 // QVariant ActMultiDropChannelNumber
    121, QMetaType::QVariant, 0x29015003, 		 // QVariant ActNetworkNumber
    125, QMetaType::QVariant, 0x29015003, 		 // QVariant ActPacketType
    127, QMetaType::QVariant, 0x29015003, 		 // QVariant ActParity
    129, QMetaType::QVariant, 0x29015003, 		 // QVariant ActPassword
    133, QMetaType::QVariant, 0x29015003, 		 // QVariant ActPortNumber
    135, QMetaType::QVariant, 0x29015003, 		 // QVariant ActProtocolType
    137, QMetaType::QVariant, 0x29015003, 		 // QVariant ActSourceNetworkNumber
    139, QMetaType::QVariant, 0x29015003, 		 // QVariant ActSourceStationNumber
    141, QMetaType::QVariant, 0x29015003, 		 // QVariant ActStationNumber
    143, QMetaType::QVariant, 0x29015003, 		 // QVariant ActStopBits
    145, QMetaType::QVariant, 0x29015003, 		 // QVariant ActSumCheck
    147, QMetaType::QVariant, 0x29015003, 		 // QVariant ActTargetSimulator
    149, QMetaType::QVariant, 0x29015003, 		 // QVariant ActThroughNetworkType
    151, QMetaType::QVariant, 0x29015003, 		 // QVariant ActTimeOut
    155, QMetaType::QVariant, 0x29015003, 		 // QVariant ActUnitNumber
    157, QMetaType::QVariant, 0x29015003, 		 // QVariant ActUnitType

    0 // eod
};

const QMetaObject ActMLProgType::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActProgTypeLib__ActMLProgType, 0, 0, 0 }
};

void *ActMLProgType::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ActProgTypeLib::ActMLProgType"))
        return static_cast<void*>(const_cast<ActMLProgType*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_ActProgTypeLib__IActMLProgType[] = {

 // content:
    7, // revision
    210,  // classname
    0, 0, // classinfo
    55, 14, // methods
    31, 542, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 289, 6, 5,
    15, 1, 298, 6, 5,
    17, 3, 301, 6, 5,

// slot: name, argc, parameters, tag, flags
    29, 0, 308, 6, 9,
    32, 4, 309, 6, 9,
    36, 0, 318, 6, 9,
    37, 7, 319, 6, 9,
    50, 2, 334, 6, 9,
    53, 2, 339, 6, 9,
    54, 2, 344, 6, 9,
    56, 0, 349, 6, 9,
    57, 4, 350, 6, 9,
    60, 3, 359, 6, 9,
    61, 3, 366, 6, 9,
    62, 3, 373, 6, 9,
    63, 3, 380, 6, 9,
    70, 1, 387, 6, 9,
    80, 1, 390, 6, 9,
    88, 1, 393, 6, 9,
    90, 1, 396, 6, 9,
    92, 1, 399, 6, 9,
    94, 1, 402, 6, 9,
    96, 1, 405, 6, 9,
    98, 1, 408, 6, 9,
    102, 1, 411, 6, 9,
    108, 1, 414, 6, 9,
    110, 1, 417, 6, 9,
    112, 1, 420, 6, 9,
    114, 1, 423, 6, 9,
    118, 1, 426, 6, 9,
    120, 1, 429, 6, 9,
    124, 1, 432, 6, 9,
    126, 1, 435, 6, 9,
    128, 1, 438, 6, 9,
    132, 1, 441, 6, 9,
    134, 1, 444, 6, 9,
    136, 1, 447, 6, 9,
    138, 1, 450, 6, 9,
    140, 1, 453, 6, 9,
    142, 1, 456, 6, 9,
    144, 1, 459, 6, 9,
    146, 1, 462, 6, 9,
    148, 1, 465, 6, 9,
    150, 1, 468, 6, 9,
    154, 1, 471, 6, 9,
    156, 1, 474, 6, 9,
    158, 7, 477, 6, 9,
    166, 1, 492, 6, 9,
    168, 2, 495, 6, 9,
    169, 2, 500, 6, 9,
    171, 4, 505, 6, 9,
    172, 3, 514, 6, 9,
    173, 3, 521, 6, 9,
    174, 3, 528, 6, 9,
    175, 3, 535, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 184, 185, 186, 182,
    QMetaType::QVariant,
    QMetaType::QVariant, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 0x80000000 | 187, 188, 189, 190, 191, 192, 193, 194,
    QMetaType::QVariant, 0x80000000 | 187, 0x80000000 | 187, 195, 196,
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 181, 197,
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 181, 197,
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 198, 199, 200, 197,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 181, 185, 197,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 181, 185, 197,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 184, 185, 197,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 187, 184, 185, 197,
    QMetaType::Void, QMetaType::QVariant, 71,
    QMetaType::Void, QMetaType::QVariant, 81,
    QMetaType::Void, QMetaType::QVariant, 89,
    QMetaType::Void, QMetaType::QVariant, 91,
    QMetaType::Void, QMetaType::QVariant, 93,
    QMetaType::Void, QMetaType::QVariant, 95,
    QMetaType::Void, QMetaType::QVariant, 97,
    QMetaType::Void, QMetaType::QVariant, 99,
    QMetaType::Void, QMetaType::QVariant, 103,
    QMetaType::Void, QMetaType::QVariant, 109,
    QMetaType::Void, QMetaType::QVariant, 111,
    QMetaType::Void, QMetaType::QVariant, 113,
    QMetaType::Void, QMetaType::QVariant, 115,
    QMetaType::Void, QMetaType::QVariant, 119,
    QMetaType::Void, QMetaType::QVariant, 121,
    QMetaType::Void, QMetaType::QVariant, 125,
    QMetaType::Void, QMetaType::QVariant, 127,
    QMetaType::Void, QMetaType::QVariant, 129,
    QMetaType::Void, QMetaType::QVariant, 133,
    QMetaType::Void, QMetaType::QVariant, 135,
    QMetaType::Void, QMetaType::QVariant, 137,
    QMetaType::Void, QMetaType::QVariant, 139,
    QMetaType::Void, QMetaType::QVariant, 141,
    QMetaType::Void, QMetaType::QVariant, 143,
    QMetaType::Void, QMetaType::QVariant, 145,
    QMetaType::Void, QMetaType::QVariant, 147,
    QMetaType::Void, QMetaType::QVariant, 149,
    QMetaType::Void, QMetaType::QVariant, 151,
    QMetaType::Void, QMetaType::QVariant, 155,
    QMetaType::Void, QMetaType::QVariant, 157,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 201, 202, 203, 204, 205, 206, 207,
    QMetaType::QVariant, QMetaType::QVariant, 208,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 198, 199, 209, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 185, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 181, 185, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 184, 185, 182,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 184, 185, 182,

 // properties: name, type, flags
    71, QMetaType::QVariant, 0x29015003, 		 // QVariant ActBaudRate
    81, QMetaType::QVariant, 0x29015003, 		 // QVariant ActConnectUnitNumber
    89, QMetaType::QVariant, 0x29015003, 		 // QVariant ActControl
    91, QMetaType::QVariant, 0x29015003, 		 // QVariant ActCpuTimeOut
    93, QMetaType::QVariant, 0x29015003, 		 // QVariant ActCpuType
    95, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDataBits
    97, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDestinationIONumber
    99, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDestinationPortNumber
    103, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDidPropertyBit
    109, QMetaType::QVariant, 0x29015003, 		 // QVariant ActDsidPropertyBit
    111, QMetaType::QVariant, 0x29015003, 		 // QVariant ActHostAddress
    113, QMetaType::QVariant, 0x29015003, 		 // QVariant ActIONumber
    115, QMetaType::QVariant, 0x29015003, 		 // QVariant ActIntelligentPreferenceBit
    119, QMetaType::QVariant, 0x29015003, 		 // QVariant ActMultiDropChannelNumber
    121, QMetaType::QVariant, 0x29015003, 		 // QVariant ActNetworkNumber
    125, QMetaType::QVariant, 0x29015003, 		 // QVariant ActPacketType
    127, QMetaType::QVariant, 0x29015003, 		 // QVariant ActParity
    129, QMetaType::QVariant, 0x29015003, 		 // QVariant ActPassword
    133, QMetaType::QVariant, 0x29015003, 		 // QVariant ActPortNumber
    135, QMetaType::QVariant, 0x29015003, 		 // QVariant ActProtocolType
    137, QMetaType::QVariant, 0x29015003, 		 // QVariant ActSourceNetworkNumber
    139, QMetaType::QVariant, 0x29015003, 		 // QVariant ActSourceStationNumber
    141, QMetaType::QVariant, 0x29015003, 		 // QVariant ActStationNumber
    143, QMetaType::QVariant, 0x29015003, 		 // QVariant ActStopBits
    145, QMetaType::QVariant, 0x29015003, 		 // QVariant ActSumCheck
    147, QMetaType::QVariant, 0x29015003, 		 // QVariant ActTargetSimulator
    149, QMetaType::QVariant, 0x29015003, 		 // QVariant ActThroughNetworkType
    151, QMetaType::QVariant, 0x29015003, 		 // QVariant ActTimeOut
    155, QMetaType::QVariant, 0x29015003, 		 // QVariant ActUnitNumber
    157, QMetaType::QVariant, 0x29015003, 		 // QVariant ActUnitType
    177, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IActMLProgType::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActProgTypeLib__IActMLProgType, 0, 0, 0 }
};

void *IActMLProgType::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ActProgTypeLib::IActMLProgType"))
        return static_cast<void*>(const_cast<IActMLProgType*>(this));
    return QAxObject::qt_metacast(_clname);
}

