/****************************************************************************
**
** Metadata for ActUtlTypeLib generated by dumpcpp v5.13.0 using
** dumpcpp {63885648-1785-41A4-82D5-C578D29E4DA8}
** from the type library C:\MELSEC\Act\Control\ActUtlType.dll
**
****************************************************************************/

#define QAX_DUMPCPP_ACTUTLTYPELIB_NOINLINES
#include "actutltypelib.h"

using namespace ActUtlTypeLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[116];
    char stringdata0[1370];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 25, 0),
QT_MOC_LITERAL(1, 26, 17, 0),
QT_MOC_LITERAL(2, 44, 18, 0),
QT_MOC_LITERAL(3, 63, 11, 0),
QT_MOC_LITERAL(4, 75, 11, 0),
QT_MOC_LITERAL(5, 87, 14, 0),
QT_MOC_LITERAL(6, 102, 0, 0),
QT_MOC_LITERAL(7, 103, 8, 0),
QT_MOC_LITERAL(8, 112, 5, 0),
QT_MOC_LITERAL(9, 118, 11, 0),
QT_MOC_LITERAL(10, 130, 9, 0),
QT_MOC_LITERAL(11, 140, 4, 0),
QT_MOC_LITERAL(12, 145, 6, 0),
QT_MOC_LITERAL(13, 152, 4, 0),
QT_MOC_LITERAL(14, 157, 4, 0),
QT_MOC_LITERAL(15, 162, 15, 0),
QT_MOC_LITERAL(16, 178, 4, 0),
QT_MOC_LITERAL(17, 183, 6, 0),
QT_MOC_LITERAL(18, 190, 4, 0),
QT_MOC_LITERAL(19, 195, 4, 0),
QT_MOC_LITERAL(20, 200, 17, 0),
QT_MOC_LITERAL(21, 218, 10, 0),
QT_MOC_LITERAL(22, 229, 5, 0),
QT_MOC_LITERAL(23, 235, 4, 0),
QT_MOC_LITERAL(24, 240, 13, 0),
QT_MOC_LITERAL(25, 254, 8, 0),
QT_MOC_LITERAL(26, 263, 14, 0),
QT_MOC_LITERAL(27, 278, 15, 0),
QT_MOC_LITERAL(28, 294, 14, 0),
QT_MOC_LITERAL(29, 309, 5, 0),
QT_MOC_LITERAL(30, 315, 7, 0),
QT_MOC_LITERAL(31, 323, 10, 0),
QT_MOC_LITERAL(32, 334, 17, 0),
QT_MOC_LITERAL(33, 352, 12, 0),
QT_MOC_LITERAL(34, 365, 13, 0),
QT_MOC_LITERAL(35, 379, 7, 0),
QT_MOC_LITERAL(36, 387, 16, 0),
QT_MOC_LITERAL(37, 404, 12, 0),
QT_MOC_LITERAL(38, 417, 7, 0),
QT_MOC_LITERAL(39, 425, 8, 0),
QT_MOC_LITERAL(40, 434, 6, 0),
QT_MOC_LITERAL(41, 441, 12, 0),
QT_MOC_LITERAL(42, 454, 7, 0),
QT_MOC_LITERAL(43, 462, 9, 0),
QT_MOC_LITERAL(44, 472, 9, 0),
QT_MOC_LITERAL(45, 482, 10, 0),
QT_MOC_LITERAL(46, 493, 9, 0),
QT_MOC_LITERAL(47, 503, 10, 0),
QT_MOC_LITERAL(48, 514, 9, 0),
QT_MOC_LITERAL(49, 524, 10, 0),
QT_MOC_LITERAL(50, 535, 7, 0),
QT_MOC_LITERAL(51, 543, 4, 0),
QT_MOC_LITERAL(52, 548, 10, 0),
QT_MOC_LITERAL(53, 559, 8, 0),
QT_MOC_LITERAL(54, 568, 8, 0),
QT_MOC_LITERAL(55, 577, 15, 0),
QT_MOC_LITERAL(56, 593, 16, 0),
QT_MOC_LITERAL(57, 610, 16, 0),
QT_MOC_LITERAL(58, 627, 17, 0),
QT_MOC_LITERAL(59, 645, 26, 0),
QT_MOC_LITERAL(60, 672, 23, 0),
QT_MOC_LITERAL(61, 696, 14, 0),
QT_MOC_LITERAL(62, 711, 11, 0),
QT_MOC_LITERAL(63, 723, 12, 0),
QT_MOC_LITERAL(64, 736, 5, 0),
QT_MOC_LITERAL(65, 742, 6, 0),
QT_MOC_LITERAL(66, 749, 4, 0),
QT_MOC_LITERAL(67, 754, 10, 0),
QT_MOC_LITERAL(68, 765, 5, 0),
QT_MOC_LITERAL(69, 771, 7, 0),
QT_MOC_LITERAL(70, 779, 7, 0),
QT_MOC_LITERAL(71, 787, 12, 0),
QT_MOC_LITERAL(72, 800, 10, 0),
QT_MOC_LITERAL(73, 811, 9, 0),
QT_MOC_LITERAL(74, 821, 10, 0),
QT_MOC_LITERAL(75, 832, 5, 0),
QT_MOC_LITERAL(76, 838, 11, 0),
QT_MOC_LITERAL(77, 850, 16, 0),
QT_MOC_LITERAL(78, 867, 17, 0),
QT_MOC_LITERAL(79, 885, 17, 0),
QT_MOC_LITERAL(80, 903, 18, 0),
QT_MOC_LITERAL(81, 922, 26, 0),
QT_MOC_LITERAL(82, 949, 7, 0),
QT_MOC_LITERAL(83, 957, 27, 0),
QT_MOC_LITERAL(84, 985, 20, 0),
QT_MOC_LITERAL(85, 1006, 13, 0),
QT_MOC_LITERAL(86, 1020, 9, 0),
QT_MOC_LITERAL(87, 1030, 7, 0),
QT_MOC_LITERAL(88, 1038, 13, 0),
QT_MOC_LITERAL(89, 1052, 13, 0),
QT_MOC_LITERAL(90, 1066, 7, 0),
QT_MOC_LITERAL(91, 1074, 15, 0),
QT_MOC_LITERAL(92, 1090, 9, 0),
QT_MOC_LITERAL(93, 1100, 9, 0),
QT_MOC_LITERAL(94, 1110, 10, 0),
QT_MOC_LITERAL(95, 1121, 8, 0),
QT_MOC_LITERAL(96, 1130, 14, 0),
QT_MOC_LITERAL(97, 1145, 9, 0),
QT_MOC_LITERAL(98, 1155, 11, 0),
QT_MOC_LITERAL(99, 1167, 11, 0),
QT_MOC_LITERAL(100, 1179, 12, 0),
QT_MOC_LITERAL(101, 1192, 12, 0),
QT_MOC_LITERAL(102, 1205, 9, 0),
QT_MOC_LITERAL(103, 1215, 10, 0),
QT_MOC_LITERAL(104, 1226, 10, 0),
QT_MOC_LITERAL(105, 1237, 11, 0),
QT_MOC_LITERAL(106, 1249, 7, 0),
QT_MOC_LITERAL(107, 1257, 8, 0),
QT_MOC_LITERAL(108, 1266, 6, 0),
QT_MOC_LITERAL(109, 1273, 12, 0),
QT_MOC_LITERAL(110, 1286, 7, 0),
QT_MOC_LITERAL(111, 1294, 9, 0),
QT_MOC_LITERAL(112, 1304, 9, 0),
QT_MOC_LITERAL(113, 1314, 12, 0),
QT_MOC_LITERAL(114, 1327, 12, 0),
QT_MOC_LITERAL(115, 1340, 28, 0)
    },
    "ActUtlTypeLib::ActUtlType\0Event Interface 1\0_IActUtlTypeEvents\0Interface 0\0"
    "IActUtlType\0OnDeviceStatus\0\0szDevice\0lData\0lReturnCode\0exception\0code\0source\0"
    "disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0CheckDeviceString\0lCheckType\0"
    "lSize\0int&\0lplDeviceType\0QString&\0lpszDeviceName\0lplDeviceNumber\0lplDeviceRadix\0"
    "Close\0Connect\0Disconnect\0EntryDeviceStatus\0szDeviceList\0lMonitorCycle\0lplData\0"
    "FreeDeviceStatus\0GetClockData\0lpsYear\0lpsMonth\0lpsDay\0lpsDayOfWeek\0lpsHour\0"
    "lpsMinute\0lpsSecond\0GetCpuType\0szCpuName\0lplCpuCode\0GetDevice\0GetDevice2\0"
    "lpsData\0Open\0ReadBuffer\0lStartIO\0lAddress\0ReadDeviceBlock\0ReadDeviceBlock2\0"
    "ReadDeviceRandom\0ReadDeviceRandom2\0SetActLogicalStationNumber\0ActLogicalStationNumber\0"
    "SetActPassword\0ActPassword\0SetClockData\0sYear\0sMonth\0sDay\0sDayOfWeek\0sHour\0"
    "sMinute\0sSecond\0SetCpuStatus\0lOperation\0SetDevice\0SetDevice2\0sData\0WriteBuffer\0"
    "WriteDeviceBlock\0WriteDeviceBlock2\0WriteDeviceRandom\0WriteDeviceRandom2\0"
    "ActUtlTypeLib::IActUtlType\0control\0ActUtlTypeLib::ActMLUtlType\0_IActMLUtlTypeEvents\0"
    "IActMLUtlType\0varDevice\0varData\0varReturnCode\0varDeviceList\0varSize\0"
    "varMonitorCycle\0QVariant&\0lpvarYear\0lpvarMonth\0lpvarDay\0lpvarDayOfWeek\0"
    "lpvarHour\0lpvarMinute\0lpvarSecond\0lpvarCpuName\0lpvarCpuCode\0lpvarData\0"
    "varStartIO\0varAddress\0varReadSize\0varYear\0varMonth\0varDay\0varDayOfWeek\0varHour\0"
    "varMinute\0varSecond\0varOperation\0varWriteSize\0ActUtlTypeLib::IActMLUtlType\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_ActUtlTypeLib__ActUtlType[] = {

 // content:
    7, // revision
    0,  // classname
    2, 14, // classinfo
    31, 18, // methods
    2, 366, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 

// signal: name, argc, parameters, tag, flags
    5, 3, 173, 6, 5,
    10, 4, 180, 6, 5,
    15, 1, 189, 6, 5,
    17, 3, 192, 6, 5,

// slot: name, argc, parameters, tag, flags
    20, 7, 199, 6, 9,
    29, 0, 214, 6, 9,
    30, 0, 215, 6, 9,
    31, 0, 216, 6, 9,
    32, 4, 217, 6, 9,
    36, 0, 226, 6, 9,
    37, 7, 227, 6, 9,
    45, 2, 242, 6, 9,
    48, 2, 247, 6, 9,
    49, 2, 252, 6, 9,
    51, 0, 257, 6, 9,
    52, 4, 258, 6, 9,
    55, 3, 267, 6, 9,
    56, 3, 274, 6, 9,
    57, 3, 281, 6, 9,
    58, 3, 288, 6, 9,
    59, 1, 295, 6, 9,
    61, 1, 298, 6, 9,
    63, 7, 301, 6, 9,
    71, 1, 316, 6, 9,
    73, 2, 319, 6, 9,
    74, 2, 324, 6, 9,
    76, 4, 329, 6, 9,
    77, 3, 338, 6, 9,
    78, 3, 345, 6, 9,
    79, 3, 352, 6, 9,
    80, 3, 359, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::Int, 7, 8, 9,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 0x80000000 | 25, 0x80000000 | 23, 0x80000000 | 23, 7, 21, 22, 24, 26, 27, 28,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 33, 22, 34, 35,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 38, 39, 40, 41, 42, 43, 44,
    QMetaType::Int, 0x80000000 | 25, 0x80000000 | 23, 46, 47,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 23, 7, 35,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 23, 7, 50,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 53, 54, 22, 50,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 50,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 50,
    QMetaType::Void, QMetaType::Int, 60,
    QMetaType::Void, QMetaType::QString, 62,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 64, 65, 66, 67, 68, 69, 70,
    QMetaType::Int, QMetaType::Int, 72,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 7, 8,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 7, 75,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 53, 54, 22, 50,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 50,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 50,

 // properties: name, type, flags
    60, QMetaType::Int, 0x02015003, 		 // int ActLogicalStationNumber
    62, QMetaType::QString, 0x0a015003, 		 // QString ActPassword

    0 // eod
};

const QMetaObject ActUtlType::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActUtlTypeLib__ActUtlType, 0, 0, 0 }
};

void *ActUtlType::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ActUtlTypeLib::ActUtlType"))
        return static_cast<void*>(const_cast<ActUtlType*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_ActUtlTypeLib__IActUtlType[] = {

 // content:
    7, // revision
    81,  // classname
    0, 0, // classinfo
    30, 14, // methods
    3, 350, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 164, 6, 5,
    15, 1, 173, 6, 5,
    17, 3, 176, 6, 5,

// slot: name, argc, parameters, tag, flags
    20, 7, 183, 6, 9,
    29, 0, 198, 6, 9,
    30, 0, 199, 6, 9,
    31, 0, 200, 6, 9,
    32, 4, 201, 6, 9,
    36, 0, 210, 6, 9,
    37, 7, 211, 6, 9,
    45, 2, 226, 6, 9,
    48, 2, 231, 6, 9,
    49, 2, 236, 6, 9,
    51, 0, 241, 6, 9,
    52, 4, 242, 6, 9,
    55, 3, 251, 6, 9,
    56, 3, 258, 6, 9,
    57, 3, 265, 6, 9,
    58, 3, 272, 6, 9,
    59, 1, 279, 6, 9,
    61, 1, 282, 6, 9,
    63, 7, 285, 6, 9,
    71, 1, 300, 6, 9,
    73, 2, 303, 6, 9,
    74, 2, 308, 6, 9,
    76, 4, 313, 6, 9,
    77, 3, 322, 6, 9,
    78, 3, 329, 6, 9,
    79, 3, 336, 6, 9,
    80, 3, 343, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 0x80000000 | 25, 0x80000000 | 23, 0x80000000 | 23, 7, 21, 22, 24, 26, 27, 28,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 33, 22, 34, 35,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 0x80000000 | 23, 38, 39, 40, 41, 42, 43, 44,
    QMetaType::Int, 0x80000000 | 25, 0x80000000 | 23, 46, 47,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 23, 7, 35,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 23, 7, 50,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 53, 54, 22, 50,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 50,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 50,
    QMetaType::Void, QMetaType::Int, 60,
    QMetaType::Void, QMetaType::QString, 62,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 64, 65, 66, 67, 68, 69, 70,
    QMetaType::Int, QMetaType::Int, 72,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 7, 8,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 7, 75,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 23, 53, 54, 22, 50,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 7, 22, 50,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 35,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 0x80000000 | 23, 33, 22, 50,

 // properties: name, type, flags
    60, QMetaType::Int, 0x02015003, 		 // int ActLogicalStationNumber
    62, QMetaType::QString, 0x0a015003, 		 // QString ActPassword
    82, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IActUtlType::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActUtlTypeLib__IActUtlType, 0, 0, 0 }
};

void *IActUtlType::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ActUtlTypeLib::IActUtlType"))
        return static_cast<void*>(const_cast<IActUtlType*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_ActUtlTypeLib__ActMLUtlType[] = {

 // content:
    7, // revision
    83,  // classname
    2, 14, // classinfo
    28, 18, // methods
    2, 334, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    1, 84, 
    3, 85, 

// signal: name, argc, parameters, tag, flags
    5, 3, 158, 6, 5,
    10, 4, 165, 6, 5,
    15, 1, 174, 6, 5,
    17, 3, 177, 6, 5,

// slot: name, argc, parameters, tag, flags
    29, 0, 184, 6, 9,
    32, 4, 185, 6, 9,
    36, 0, 194, 6, 9,
    37, 7, 195, 6, 9,
    45, 2, 210, 6, 9,
    48, 2, 215, 6, 9,
    49, 2, 220, 6, 9,
    51, 0, 225, 6, 9,
    52, 4, 226, 6, 9,
    55, 3, 235, 6, 9,
    56, 3, 242, 6, 9,
    57, 3, 249, 6, 9,
    58, 3, 256, 6, 9,
    59, 1, 263, 6, 9,
    61, 1, 266, 6, 9,
    63, 7, 269, 6, 9,
    71, 1, 284, 6, 9,
    73, 2, 287, 6, 9,
    74, 2, 292, 6, 9,
    76, 4, 297, 6, 9,
    77, 3, 306, 6, 9,
    78, 3, 313, 6, 9,
    79, 3, 320, 6, 9,
    80, 3, 327, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 87, 88,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 89, 90, 91, 87,
    QMetaType::QVariant,
    QMetaType::QVariant, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 93, 94, 95, 96, 97, 98, 99,
    QMetaType::QVariant, 0x80000000 | 92, 0x80000000 | 92, 100, 101,
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 86, 102,
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 86, 102,
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 103, 104, 105, 102,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 86, 90, 102,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 86, 90, 102,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 89, 90, 102,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 89, 90, 102,
    QMetaType::Void, QMetaType::QVariant, 60,
    QMetaType::Void, QMetaType::QVariant, 62,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 106, 107, 108, 109, 110, 111, 112,
    QMetaType::QVariant, QMetaType::QVariant, 113,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 103, 104, 114, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 90, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 90, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 89, 90, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 89, 90, 87,

 // properties: name, type, flags
    60, QMetaType::QVariant, 0x29015003, 		 // QVariant ActLogicalStationNumber
    62, QMetaType::QVariant, 0x29015003, 		 // QVariant ActPassword

    0 // eod
};

const QMetaObject ActMLUtlType::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActUtlTypeLib__ActMLUtlType, 0, 0, 0 }
};

void *ActMLUtlType::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ActUtlTypeLib::ActMLUtlType"))
        return static_cast<void*>(const_cast<ActMLUtlType*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_ActUtlTypeLib__IActMLUtlType[] = {

 // content:
    7, // revision
    115,  // classname
    0, 0, // classinfo
    27, 14, // methods
    3, 318, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 149, 6, 5,
    15, 1, 158, 6, 5,
    17, 3, 161, 6, 5,

// slot: name, argc, parameters, tag, flags
    29, 0, 168, 6, 9,
    32, 4, 169, 6, 9,
    36, 0, 178, 6, 9,
    37, 7, 179, 6, 9,
    45, 2, 194, 6, 9,
    48, 2, 199, 6, 9,
    49, 2, 204, 6, 9,
    51, 0, 209, 6, 9,
    52, 4, 210, 6, 9,
    55, 3, 219, 6, 9,
    56, 3, 226, 6, 9,
    57, 3, 233, 6, 9,
    58, 3, 240, 6, 9,
    59, 1, 247, 6, 9,
    61, 1, 250, 6, 9,
    63, 7, 253, 6, 9,
    71, 1, 268, 6, 9,
    73, 2, 271, 6, 9,
    74, 2, 276, 6, 9,
    76, 4, 281, 6, 9,
    77, 3, 290, 6, 9,
    78, 3, 297, 6, 9,
    79, 3, 304, 6, 9,
    80, 3, 311, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 89, 90, 91, 87,
    QMetaType::QVariant,
    QMetaType::QVariant, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 0x80000000 | 92, 93, 94, 95, 96, 97, 98, 99,
    QMetaType::QVariant, 0x80000000 | 92, 0x80000000 | 92, 100, 101,
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 86, 102,
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 86, 102,
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 103, 104, 105, 102,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 86, 90, 102,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 86, 90, 102,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 89, 90, 102,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 92, 89, 90, 102,
    QMetaType::Void, QMetaType::QVariant, 60,
    QMetaType::Void, QMetaType::QVariant, 62,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 106, 107, 108, 109, 110, 111, 112,
    QMetaType::QVariant, QMetaType::QVariant, 113,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 103, 104, 114, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 90, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 86, 90, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 89, 90, 87,
    QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 89, 90, 87,

 // properties: name, type, flags
    60, QMetaType::QVariant, 0x29015003, 		 // QVariant ActLogicalStationNumber
    62, QMetaType::QVariant, 0x29015003, 		 // QVariant ActPassword
    82, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IActMLUtlType::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActUtlTypeLib__IActMLUtlType, 0, 0, 0 }
};

void *IActMLUtlType::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ActUtlTypeLib::IActMLUtlType"))
        return static_cast<void*>(const_cast<IActMLUtlType*>(this));
    return QAxObject::qt_metacast(_clname);
}

